# File containing constants used for waypoint actions

# options for endcondition field
PATHACTION_ENDCONDITION_NONE = 0
PATHACTION_ENDCONDITION_TIMEOUT = 1
PATHACTION_ENDCONDITION_DISTANCETOTARGET = 2
PATHACTION_ENDCONDITION_LEGREMAINING = 3
PATHACTION_ENDCONDITION_BELOWERROR = 4
PATHACTION_ENDCONDITION_ABOVEALTITUDE = 5
PATHACTION_ENDCONDITION_ABOVESPEED = 6
PATHACTION_ENDCONDITION_POINTINGTOWARDSNEXT = 7
PATHACTION_ENDCONDITION_PYTHONSCRIPT = 8
PATHACTION_ENDCONDITION_IMMEDIATE = 9

# options for mode parameters
PATHACTION_MODE_GOTOENDPOINT = 0
PATHACTION_MODE_FOLLOWVECTOR = 1
PATHACTION_MODE_CIRCLERIGHT = 2
PATHACTION_MODE_CIRCLELEFT = 3
PATHACTION_MODE_FIXEDATTITUDE = 4
PATHACTION_MODE_SETACCESSORY = 5
PATHACTION_MODE_DISARMALARM = 6
PATHACTION_MODE_LAND = 7
PATHACTION_MODE_BRAKE = 8
PATHACTION_MODE_VELOCITY = 9
PATHACTION_MODE_AUTOTAKEOFF = 10

# options for commands
PATHACTION_COMMAND_ONCONDITIONNEXTWAYPOINT = 0
PATHACTION_COMMAND_ONNOTCONDITIONNEXTWAYPOINT = 1
PATHACTION_COMMAND_ONCONDITIONJUMPWAYPOINT = 2
PATHACTION_COMMAND_ONNOTCONDITIONJUMPWAYPOINT = 3
PATHACTION_COMMAND_IFCONDITIONJUMPWAYPOINTELSENEXTWAYPOINT = 4
